package basilisk.web.servlet; 
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import java.util.HashMap;
import java.util.Map;

@RestController
public class BasiliskKeyExchangeEndpoint {

	@PostMapping("/exchange-keys")
	public Map<String, String> keyExchange (@RequestBody Map<String, String> request) {
		String clientPublicKey = request.get("Got the public key");
		String serverPublicKey = "Public Key generated by server";
		Map<String, String> response = new HashMap<>();
		response.put("The server public key", serverPublicKey);
		return response;
	}

	@GetMapping("/data/data/1")
	public String getData(@RequestParam(value = "id", defaultValue = "1") String id) {
		return "The Sample Data for ID: " + id;
	}
}

