package basilisk.web.servlet; 

import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
import java.util.HashMap;

@RestController
@RequestMapping("/api")
public class BasiliskKeyExchangeEndpoint {
	private Map<String, String> publicStoreKey = new HashMap<>();
	@PostMapping("/exchange-keys")
	public Map<String, String> keyExchange (@RequestBody Map<String, String> request) {
		String theClientPublicKey = request.get("Got the public key");
		String serverPublicKey = "Public Key generated by server";
		publicStoreKey.put("Client", theClientPublicKey);
		Map<String, String> response = new HashMap<>();
		response.put("The server public key", serverPublicKey);
		return response;
	}

	@GetMapping("/data/{id}")
	public String dataRetrieval(@PathVariable String id) {
		return "The Sample Data for ID: " + id;
}
}

